# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'dist/**'  # Ignore changes in the dist directory to avoid triggering the workflow again
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # Copy .d.ts files from src to dist directory
    - name: Copy .d.ts files
      if: success()
      run: cp -r src/*.d.ts dist/

    # Upload build artifacts from the /dist directory
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/

    # Commit and push the build artifacts in the /dist directory
    - name: Commit build artifacts
      if: success()
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add dist/
        git commit -m "add build artifacts [skip ci]"
        git push origin ${{ github.ref }}
